## Introdução
Este banco de dados é uma filtragem do TMDB (The Movie Database), incluindo apenas os filmes de horror. A filtragem obedeceu aos critérios de:

* Gênero deve incluir **Horror**
* A **média de classificação** ser maior do que 7.0
* O filme tem uma **contagem de votos** acima de 100.


Colunas do banco de dados:
* title: Título do filme.
* id: Identificador de cada filme.
* overview: Uma breve sinopse do filme.
* genres: Gêneros associados ao filme.
* cast: Atores principais do filme.
* director: Diretor do filme.
* writers: Escritores do filme.
* production_companies: Companhias envolvidas na produção do filme.
* producers: Produtores que trabalharam no filme.
* original_language: Idioma em que o filme foi originalmente produzido.
* vote_average: Média de classificação do filme.
* vote_count: Número total de votos para o filme.
* runtime: Duração do filme em minutos.
* release_date: Data de lançamento do filme.

## Instalação e Tratamento dos Dados

In [2]:
import pandas as pd

In [ ]:
# Importando o arquivo
df_backup = pd.read_csv('horror-movies.csv')
df_backup.head()

,title,id,overview,genres,cast,director,writers,production_companies,producers,original_language,vote_count,vote_average,popularity,runtime,release_date
0,The Conjuring 2,259693,Lorraine and Ed Warren travel to north London ...,Horror,"Vera Farmiga, Madison Wolfe, Simon Delaney, Ja...",James Wan,"David Leslie Johnson-McGoldrick, Carey Hayes, ...","New Line Cinema, The Safran Company, Atomic Mo...","Peter Safran, James Wan, Dave Neustadter, Rich...",en,8024,7.292,123.168,134,2016-06-08
1,A Nightmare on Elm Street,377,Teenagers in a small town are dropping like fl...,Horror,"John Saxon, Jack Shea, Donna Woodrum, Ronee Bl...",Wes Craven,Wes Craven,"New Line Cinema, Smart Egg Pictures, Media Hom...","Stanley Dudelson, Joseph Wolf, Sara Risher, Jo...",en,4823,7.332,54.918,91,1984-11-09
2,[REC],8329,A television reporter and cameraman follow eme...,"Horror, Mystery","Ben Temple, Carlos Vicente, Kao Chen-Min, Marí...","Jaume Balagueró, Paco Plaza","Jaume Balagueró, Paco Plaza, Luiso Berdejo","Filmax, Castelao Productions, Canal+ España, T...","Carlos Fernández, Julio Fernández",es,4147,7.193,31.367,78,2007-11-23
3,The Birds,571,Thousands of birds flock into a seaside town a...,Horror,"Mike Monteleone, Doreen Lang, Charles McGraw, ...",Alfred Hitchcock,"Daphne du Maurier, Evan Hunter",Alfred J. Hitchcock Productions,Alfred Hitchcock,en,3859,7.524,30.346,120,1963-03-28
4,The Evil Dead,764,Five vacationing college students unwittingly ...,Horror,"Bob Dorian, Cheryl Guttridge, Dorothy Tapert, ...",Sam Raimi,Sam Raimi,"Renaissance Pictures, New Line Cinema","Sam Raimi, Gary Holt, Bruce Campbell, Robert T...",en,3748,7.308,35.664,85,1981-09-10

In [ ]:
# Verificando informações da base, bm como tamanho e tipos de dados
df_backup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 206 non-null    object
 1   id                    206 non-null    int64
 2   overview              206 non-null    object
 3   genres                206 non-null    object
 4   cast                  206 non-null    object
 5   director              206 non-null    object
 6   writers               206 non-null    object
 7   production_companies  206 non-null    object
 8   producers             206 non-null    object
 9   original_language     206 non-null    object
 10  vote_count            206 non-null    int64
 11  vote_average          206 non-null    float64
 12  popularity            206 non-null    float64
 13  runtime               206 non-null    int64
 14  release_date          206 non-null    object
dtypes: float64(2), int64(3), object(10)
memory usage: 24.3+ KB

Limpeza dos dados para análise.

In [ ]:
# Fazendo uma cópia da base para trabalhar com mais segurança
df = df_backup.copy()

In [9]:
df.shape

(206, 15)

In [ ]:
# Conferindo as colunas existentes
df.columns

Index(['title', 'id', 'overview', 'genres', 'cast', 'director', 'writers',
       'production_companies', 'producers', 'original_language', 'vote_count',
       'vote_average', 'popularity', 'runtime', 'release_date'],
      dtype='object')

In [ ]:
# Remoção de colunas que não serão utilizadas nesta análise
df.drop(["overview", "vote_count"], axis=1, inplace=True)

In [15]:
df.columns

Index(['title', 'id', 'genres', 'cast', 'director', 'writers',
       'production_companies', 'producers', 'original_language',
       'vote_average', 'popularity', 'runtime', 'release_date'],
      dtype='object')

In [ ]:
# Conferindo dados nulos na base
nulos = df.isnull().sum()
print(nulos)

title                   0
id                      0
genres                  0
cast                    0
director                0
writers                 0
production_companies    0
producers               0
original_language       0
vote_average            0
popularity              0
runtime                 0
release_date            0
dtype: int64

In [ ]:
# CXonferindo duplicatas na base
duplicados = df.duplicated().sum()
print(duplicados)

0

In [ ]:
# Tansformando os dados da coluna 'release_date' pra o formato de data
df['release_date'] = pd.to_datetime(df['release_date'], format="mixed")

In [ ]:
# Conferindo se o tratamento foi bem sucedido
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 206 non-null    object
 1   id                    206 non-null    int64
 2   genres                206 non-null    object
 3   cast                  206 non-null    object
 4   director              206 non-null    object
 5   writers               206 non-null    object
 6   production_companies  206 non-null    object
 7   producers             206 non-null    object
 8   original_language     206 non-null    object
 9   vote_average          206 non-null    float64
 10  popularity            206 non-null    float64
 11  runtime               206 non-null    int64
 12  release_date          206 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 21.1+ KB

In [21]:
df.describe()

,id,vote_average,popularity,runtime,release_date
count,2.060000e+02,206.000000,206.000000,206.000000,206
mean,1.614418e+05,7.383942,32.373223,101.655340,1990-07-10 05:35:32.038834944
min,1.360000e+02,7.001000,5.548000,5.000000,1920-02-27 00:00:00
25%,4.312000e+03,7.141750,14.903500,91.000000,1974-12-28 00:00:00
50%,2.233650e+04,7.332000,22.115000,103.000000,1996-02-29 12:00:00
75%,2.455215e+05,7.522500,35.195250,114.750000,2013-12-03 00:00:00
max,1.150394e+06,8.400000,381.745000,277.000000,2023-11-03 00:00:00
std,2.571398e+05,0.284084,35.576335,28.211789,NaN

In [23]:
# Exportando a base tratada
df.to_csv('Horror_Movies_B.csv', sep=';', index=False)

## Analisando os Dados